"""Constants for Indego integration."""
DOMAIN = "indego"
DATA_UPDATED = f"{DOMAIN}_data_updated"
CONF_ATTR = "attributes"
CONF_SEND_COMMAND = "command"
CONF_SMARTMOWING = "enable"
CONF_DELETE_ALERT ="alert_index"
CONF_READ_ALERT ="alert_index"
CONF_DOWNLAD_MAP = "filename"
CONF_POLLING = "polling"
DEFAULT_NAME = "Indego"
DEFAULT_NAME_COMMANDS = None
DEFAULT_MAP_NAME = "mapWithoutIndego"
SERVICE_NAME_COMMAND = "command"
SERVICE_NAME_DELETE_ALERT = "delete_alert"
SERVICE_NAME_READ_ALERT = "read_alert"
SERVICE_NAME_DELETE_ALERT_ALL = "delete_alert_all"
SERVICE_NAME_READ_ALERT_ALL = "read_alert_all"
SERVICE_NAME_SMARTMOW = "smartmowing"
SERVICE_NAME_DOWNLOAD_MAP = "download_map"
SENSOR_TYPE = "sensor"
BINARY_SENSOR_TYPE = "binary_sensor"
INDEGO_COMPONENTS = [SENSOR_TYPE, BINARY_SENSOR_TYPE]
#online
ENTITY_ONLINE = "online"
#indego.update_alerts()
ENTITY_ALERT = "alert"
ENTITY_MOWER_ALERT = "mower_alert"
ENTITY_ALERT_COUNT = "alert_count"
ENTITY_ALERT_ID = "alert_id"
ENTITY_ALERT_ERROR_CODE = "alert_errorcode"
ENTITY_ALERT_HEADLINE = "alert_headline"
ENTITY_ALERT_DATE = "alert_date"
ENTITY_ALERT_MESSAGE = "alert_message"
ENTITY_ALERT_READ_STATUS = "alert_read_status"
ENTITY_ALERT_FLAG = "alert_flag"
ENTITY_ALERT_PUSH = "alert_push"
ENTITY_ALERT_DESCRIPTION = "alert_description"
#indego.update_updates_available()
ENTITY_UPDATE_AVAILABLE = "update_available"
#indego.state_description
ENTITY_MOWER_STATE = "mower_state"
#indego.state_description_detail
ENTITY_MOWER_STATE_DETAIL = "mower_state_detail"
#indego.update_last_completed_mow()
ENTITY_LAST_COMPLETED = "last_completed"
#indego.update_next_mow()
ENTITY_NEXT_MOW = "next_mow"
#indego.update_location()
ENTITY_TIMEZONE = "location_timezone"
ENTITY_LATITUDE = "location_latitude"
ENTITY_LONGITUDE = "location_longitude"
#indego.update_setup()
ENTITY_HAS_INTEGRITY_CHECK ="setup_has_integrity_check_passed"
ENTITY_HAS_AUTO_CAL ="setup_has_auto_cal"
ENTITY_HAS_MAP ="setup_has_map"
ENTITY_HAS_PIN ="setup_has_pin"
ENTITY_HAS_OWNER ="setup_has_owner"
#indego.update_security()
ENTITY_ENABLED ="security_enabled"
ENTITY_AUTOLOCK ="security_autolock"
#indego.update_users()
ENTITY_EMAIL ="user_email"
ENTITY_DISPLAYNAME ="user_displayname"
ENTITY_LANGUAGE ="user_language"
ENTITY_COUNTRY  ="user_country"
ENTITY_OPTIN ="user_optin"
ENTITY_OPTINAPP ="user_optinapp"
#indego.update_config()
ENTITY_REGION ="config_region"
ENTITY_BORDER_CUT ="config_border_cut"
ENTITY_IS_PIN_SET ="config_is_pin_set"
ENTITY_WIRE_ID ="config_wire_id"
ENTITY_BUMP_SENSITIVITY ="config_bump_sensitivity"
ENTITY_ALARM_MODE ="config_alarm_mode"
#indego.update_generic_data()
ENTITY_NAME = "generic_data_name"
ENTITY_SERIAL = "generic_data_serialnumber"
ENTITY_SERVICECOUNTER = "generic_data_service_counter"
ENTITY_NEEDSSERVICE ="generic_data_needs_service"
ENTITY_MODELNUMBER = "generic_data_moddelnumber"
ENTITY_FIRMWARE = "generic_data_firmwareversion"
ENTITY_MODEL_DESCRIPTION ="generic_data_model_description"
ENTITY_MOWING_MODE_DESCRIPTION ="generic_data_mowing_mode_description"
#indego.update_generic_data() - voltage
ENTITY_MODEL_VOLTAGE_MIN ="generic_data_model_voltage_min"
ENTITY_MODEL_VOLTAGE_MAX ="generic_data_model_voltage_max"
#indego.update_state() 
ENTITY_STATE = "state_state"
ENTITY_MAP_UPDATE_AVAILABLE ="state_map_update_available"
ENTITY_MOWMODE ="state_mowmode"
ENTITY_LAWN_MOWED = "state_lawn_mowed"
ENTITY_XPOS = "state_x_pos"
ENTITY_YPOS = "state_y_pos"
ENTITY_MAPSVGCACHETS = "state_map_svg_cache_ts"
ENTITY_YSVGPOS = "state_svg_y_pos"
ENTITY_XSVGPOS = "state_svg_x_pos"
ENTITY_CONFIG_CHANGE ="state_config_change"
ENTITIY_MOW_TRIG ="state_mow_trig"
#indego.update_state() - Runtime total
ENTITY_RUNTIME_TOTAL_CHARGING ="runtime_total_charging"
ENTITY_RUNTIME_TOTAL_MOWING ="runtime_total_mowing"
ENTITY_RUNTIME_TOTAL_OPERATION ="runtime_total_operatiom"
#indego.update_state() - Runtime last
ENTITY_RUNTIME_LAST_CHARGING ="runtime_last_charging"
ENTITY_RUNTIME_LAST_MOWING ="runtime_last_mowing"
ENTITY_RUNTIME_LAST_OPERATION="runtime_last_operation" 
#indego.update_operating_data()
ENTITY_HMIKEYSN ="operatingdata_hmikeysn"
#indego.update_operating_data() - Battery
ENTITY_BATTERY_PRECENT = "operatingdata_battery_percent"
ENTITY_BATTERY_VOLTAGE= "operatingdata_battery_voltage"
ENTITY_BATTERY_CYCLES = "operatingdata_battery_cycles"
ENTITY_BATTERY_DISCHARGE = "operatingdata_battery_discharge"
ENTITY_BATTERY_AMBIENTE_TEMP = "operatingdata_battery_ambiente_temo"
ENTITY_BATTERY_TEMP = "operatingdata_battery_temp"
ENTITY_BATTERY_PERCENT_ADJUSTED = "operatingdata_battery_percent_adjusted"
#indego.update_operating_data() - Garden
ENTITY_ID ="operatingdata_garden_id"
ENTITY_GARDEN_NAME ="operatingdata_garden_name"
ENTITY_SIGNALID ="operatingdata_garden_signal_id"
ENTITY_SIZE ="operatingdata_garden_size"
ENTITY_INNERBOUNDS ="operatingdata_garden_innerbounds"
ENTITY_BUMPS ="operatingdata_garden_bumps"
ENTITY_STOPS ="operatingdata_garden_stops"
ENTITY_GARDEN_LASTMOW ="operatingdata_garden_last_mow"
ENTITY_MAPCELLSIZE ="operatingdata_garden_mapcellsize"
#indego.update_next_mow()
ENTITY_MCC ="network_mcc"
ENTITY_MNC ="network_mnc"
ENTITY_RSSI ="network_rssi"
ENTITY_CURRMODE ="network_currmode"
ENTITY_CONFIGMODE ="network_configmode"
ENTITY_STEEREDRSSI ="network_steeredrssi"
ENTITY_NETWORKCOUNT ="network_networkcount"